# ORDENA OS NOMES POR ORDEM DECRESCENTE
SELECT * FROM cursos
ORDER BY nome desc;

# ORDENA POR NOME
SELECT * FROM cursos
ORDER BY nome;

# ORDENA POR ANO E NOME
SELECT nome, ano FROM cursos ORDER BY ano, nome;

#---------- FILTRANDO LINHAS ----------

# FILTRA AS COLUNAS NOME, CARGA, TOTAAULAS, ONDE O ANO SEJA IGUAL A 2016 E TOTAULAS IGUAL A 15
SELECT nome, carga, totaulas FROM cursos
WHERE ano = 2016 && totaulas = 15
ORDER BY nome;


# A PALAVRA BETWEEN QUER DIZER "ENTRE"
SELECT * FROM cursos
WHERE  ano BETWEEN 2016 AND 2018
ORDER BY ano, nome;

# ONDE OS ANO SEJA 2014 E 2018
SELECT * FROM cursos
WHERE  ano IN (2014, 2018)
ORDER BY ano DESC, nome ASC;